/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#003e7a",
        "primary-container": "#0055a4",
        "on-primary": "#ffffff",
        "on-primary-container": "#afccff",
        "primary-fixed": "#d5e3ff",
        "primary-fixed-dim": "#a8c8ff",
        "on-primary-fixed": "#001b3c",
        "on-primary-fixed-variant": "#004689",
        "secondary": "#006685",
        "secondary-container": "#6cd2ff",
        "secondary-fixed": "#bfe9ff",
        "secondary-fixed-dim": "#6cd2ff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#005975",
        "on-secondary-fixed": "#001f2a",
        "on-secondary-fixed-variant": "#004d65",
        "tertiary": "#6b0085",
        "tertiary-container": "#8a1fa6",
        "tertiary-fixed": "#fdd6ff",
        "tertiary-fixed-dim": "#f3aeff",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#f5b4ff",
        "on-tertiary-fixed": "#340042",
        "on-tertiary-fixed-variant": "#790096",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "surface-bright": "#f8f9fa",
        "surface-container": "#edeeef",
        "surface-container-low": "#f3f4f5",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#175ead",
        "surface-variant": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-surface-variant": "#424751",
        "on-background": "#191c1d",
        "background": "#f8f9fa",
        "outline": "#727783",
        "outline-variant": "#c2c6d3",
        "inverse-surface": "#2e3132",
        "inverse-on-surface": "#f0f1f2",
        "inverse-primary": "#a8c8ff",
      },
      fontFamily: {
        logo: ["Saira Stencil One", "sans-serif"],
        display: ["Merriweather", "serif"],
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
